### ISSUE TITLE
LinkReferenceDefinition followed by setText with blank line

### ISSUE THREAD

**Issue by xoofx** [commonmark/commonmark-spec#395]
How the following should be parsed?

```
[foo]: 
  /url
  "title"
Test
====

[foo]
```

While implementing my parser, I'm generating a LinkReferenceDefinition and a proper Setext heading But with the default CommonMark implem, it treats Settext  heading as a plain paragraph.

In my implems it outputs:

``` html
<h1>Test</h1>
<a href="/url" title="title">foo</a>
```

but [cmark generates this](http://johnmacfarlane.net/babelmark2/?text=[foo]%3A+%0A++%2Furl%0A++%22title%22%0ATest%0A%3D%3D%3D%3D%0A%0A[foo]):

``` html
<h1>[foo]:
/url
&quot;title&quot;
Test</h1>
<p>[foo]</p>
```

**Comment by jgm** [comment]
Actually, current cmark gives:

<h1>[foo]:
/url
&quot;title&quot;
Test</h1>
<p>[foo]</p>

The spec is currently unclear about this.  It says that a link
reference definition cannot interrupt a paragraph, but it doesn't
say anything about whether a paragraph or another block element,
like a header, can directly follow it, without intervening blank space.

The parsers use the following method:  when they've accumulated
a bunch of lines of paragraph text, they first try to see if
the initial lines can be parsed as link reference definitions.
Anything that remains is still a paragraph.  But in this case
the whole thing is being taken as a multiline setext header,
so the parsing for reference link defs doesn't occur.

+++ Alexandre Mutel [Feb 19 16 01:29 ]:

**Comment by jgm** [comment]
I think this is really an implementation bug rather than a problem with the spec.
The spec says that the lines that form the content of a setext header must be such that, in the absence of the header line, they'd form a paragraph.  That's not the case in this example; they'd form a link definition + a paragraph.

So the implementation needs to be fixed; we need to resolve link references before generating a setext header (and check that there's still some residual paragraph content left).

**Comment by xoofx** [comment]
> So the implementation needs to be fixed; we need to resolve link references before generating a setext header (and check that there's still some residual paragraph content left).

Yes, that's what I'm doing in markdig

**Comment by mgeier** [comment]
I think this is related to #461.

Not only link reference definitions have to be stripped, (after that) also leading and trailing whitespace.
Only if something is left then, a setext header or paragraph should be created.

There is still a problem, though:

```
[a]: b
======
```

If there is nothing left to turn this into a setext header, what's supposed to happen with the line of equals signs?

markdig seems to swallow them: http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Ba%5D%3A+b%0A%3D%3D%3D%3D%3D%3D.
@xoofx This doesn't sound right to me.

The problem is that checking for the link reference definition should IMHO be "undoable".
This is how I imagine a parser could "think" about the above input:

* Does the line `[a]: b` create a block? -> No. Do nothing, but keep the line somewhere.
* Does the line `======` create a block? -> Possibly, if the preceding lines look like inline content.
  * But wait! We also have to check for link reference definitions!
  * It happens that the previous line is a valid link reference definition
  * But wait! No inline content is left, so this isn't a setext header after all!
  * We should try if the line `======` creates some other block.
  * But for that to make sense, we have to undo the parsing of the link reference definition and keep the line `[a]: b` for later use, right?
  * It turns out that `======` doesn't create a block in this case, let's do nothing, but keep the line somewhere (together with the un-parsed line `[a]: b` from before)
* End of input. We should check if we kept some lines and handle them now
  * Check (again) for link reference definition. We found one, let's keep it!
  * After stripping leading and trailing whitespace, there is still one line of `======` left, we should put it into a paragraph!
* Done.

Does this sound reasonable?

Checking if the line `======` creates some other block (other than a setext header) might look superfluous, but I think it is nicer for potential extensions to keep this step.

Also, it would seem strange to me if the parser creates a link reference while parsing something that in the end turns out to be no match.

**Comment by mity** [comment]
Consider also e.g.
```
 * * * [a]: b
```

Using similar arguments, this may be
1. a list (nested in a list, nested in a list) which contains text `[a]: b`
2. a list (nested in a list, nested in a list) which contains nothing (because `[a]: b` is eaten off as a link ref. def.)
3. thematic rule (because after eating `[a]: b` as a link ref. def., there is nothing left after the asterisks)

From some intuitive point of view, I would say it should be the 2nd interpretation, i.e. that we do not re-interpret the outer context if the paragraph degenerates into nothing. Then, due consistency, I would tend to apply the same rule to the preceding examples.

**Comment by jgm** [comment]
Martin Mitáš <notifications@github.com> writes:

> From some intuitive point of view, I would say it should be the 2nd interpretation, i.e. that we do not re-interpret the outer context if the paragraph degenerates into nothing. Then, due consistency, I would tend to apply the same rule to the preceding examples.

I agree.

**Comment by jgm** [comment]
Fixed cmark.  Now we just need some examples in the spec to illustrate this.

**Comment by mity** [comment]
> Fixed cmark. Now we just need some examples in the spec to illustrate this.

For 
```
[a]: b
======
```
it now gets 
``` html
<p>======</p>
```

which little bit surprised me. My flow of thoughts is more like
1. We have a paragraph followed by settext underline.
2. We eat all refdefs from it and get empty degenerated paragraph.
3. Instead of rendering `<h1></h1>` we render nothing similarly as we do not emit `<p></p>` for a stand-alone ref. def.

Either way we go, I am also wondering whether ATX headers should not be handled the same way.

```
### [a]: b
```

to render either 
``` html
<p>###</p>
```

or empty output:
``` html
```

**Comment by jgm** [comment]
My reasoning was this:  the line
```
[a]: b
```
is consumed as a reference link definition. That's a type of block element.  So the next thing we see is
```
======
```
which isn't a setext header, because there's no preceding text.

As for ATX headers:  their contents are inline-level, not block-level. Reference link defs are block-level elements, so they can't go there.

**Comment by mity** [comment]
I can live with it. But it means the "outer context rule" actually is "preceding context rule".

**Comment by jgm** [comment]
> But it means the "outer context rule" actually is "preceding context rule".

Can you explain what you mean?

What makes this confusing is the way parsing is implemented.  Reference link definitions can span multiple lines, so in order to avoid backtracking, we don't treat them as separate block-level elements in parsing; instead, we do this trick of parsing paragraph lines and then seeing if some initial segment is actually link reference definitions.  But that's a trick, for efficiency.  Conceptually, as the spec defines them, reference link definitions are block level elements.  So, there is no more reason for
```
[a]: b
====
```
to give you an empty header than for
```
- - - - -
===
```
In both cases, we have two block-level elements. The second is just a string of `=`s and gets parsed as literal content.

**Comment by mity** [comment]
Well. Maybe it is subtle but lets compare 

```
 * * * [a]: /b
```

and 

```
[a]: /b
=====
```

|    | List case                      | SeText header case                    |
|----|--------------------------------|---------------------------------------|
| 1. | We have a paragraph inside a list item      | We have a paragraph followed by the SeText underline |
| 2. | The paragraph degenerates to nothing | The paragraph degenerates to nothing  |
| 3. | We do not reinterpret as hrule | We do not reinterpret as a standalone paragraph | 
| 4. | So we have an empty list item block (with some nesting) | So we have empty header block |
| 5. | We render empty list item      | We render an empty header             |
| 6. | We do not output empty `<p></p>` in it (even if the list item contains other block.) | We do not output empty `<h1></h1>` |

The 1st line of the table is what I tend to see "the other context"; and that by outputting the `=====` we reinterpret part of it after the block contents degenerates into nothing.

**Comment by jgm** [comment]
I understand better now. The issue is really #3:  "we do not reinterpret as hrule."  I hadn't thought about the hrule interpretation.

Still, I am not persuaded.  We need to think of this from the point of view of the spec, not the implementation (which as noted uses a kind of trick to handle reference link definitions).

List items can contain block-level content.  A link ref definition is block-level content.  An hrule can't have any non-space content after the final `*`, so that interpretation is ruled out.
