### ISSUE TITLE
is [a](<b)c> supposed to be an inline link?

### ISSUE THREAD

**Issue by mgeier** [commonmark/commonmark-spec#473]
See https://talk.commonmark.org/t/why-is-a-b-c-not-parsed-as-an-inline-link/2436.

It is obvious that both `[a](<b)c` and `[a](<b)c>)` are inline links, but why is `[a](<b)c>` not parsed as inline link followed by `c>` in most (or even all?) CommonMark-conformant parsers?

http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Ba%5D(%3Cb)c%3E

IMHO, `<b` is a valid "link destination", therefore `[a](<b)c>` should be parsed as inline link.

And if that's not desired, the spec should be changed accordingly.

**Comment by aidantwoods** [comment]
IMO `[a](<b)c>` should indeed be parsed as

```html
<p><a href="%3Cb">a</a>c&gt;</p>
```

To add to your examples, the reference parser will treat `[a](<b) c>` as an inline link also.

Reasoning for the discrepancy (to me) would seem like the reference parser has categorised the [destination](http://spec.commonmark.org/0.27/#link-destination) of type one too early, and upon failure for that to fully qualify as a link it (incorrectly by spec) is not attempting to interpret the destination as type two.

---

For what it's worth, my (in-progress) implementation of the spec parses `[a](<b)c>` as a link followed by `c>` (though that's probably biased to be the same as to my interpretation).

**Comment by mgeier** [comment]
A probably related example:

    [a](<b>c)

This clearly doesn't match the first clause of [link destination](http://spec.commonmark.org/0.27/#link-destination), but IMHO it should match the second clause. Therefore it should turn into a valid link.

Most (all?) CommonMark implementations disagree: http://johnmacfarlane.net/babelmark2/?text=%5Ba%5D(%3Cb%3Ec).

**Comment by aidantwoods** [comment]
I wonder whether that case is to do with precedence of raw html which binds more tightly than link text (http://spec.commonmark.org/0.27/#link-text).

(Previous examples wouldn't qualify though due to intermediary non-wordy characters)

**Comment by mity** [comment]
I agree that, as of the specs 0.27, it seems as a bug in the implementations.

> Reasoning for the discrepancy (to me) would seem like the reference parser has categorised the destination of type one too early, and upon failure for that to fully qualify as a link it (incorrectly by spec) is not attempting to interpret the destination as type two.

Well, as [MD4C](https://github.com/mity/md4c) author, I can confirm this is exactly the reason in that implementation. 

Although it was not a knowing decision (the given example simply did not come to my mind), it is obviously much simpler for implementation to do such decision as early as possible, as well as it is easier for anybody who reads and tries understand the code.

I would also like to point that the attempt to re-interpret it as a link with different type of link type may mean re-scanning rest of whole paragraph. The problem with inline links is that parsing the '(...)' portion already is quite complicated so parsing links brings that danger even without this particular issue.

Consider this:

```
[a](b "xxx
[a](b 'xxx
[a](b (xxx
Imagine long paragraph text here.
```

The snippet shows various un-closed inline links which all force parser to scan till the end of the paragraph in hope it will be able to find the proper closer of the link title and the link itself, so almost whole paragraph can have to be scanned many times.

I think we have complexity `O(m * n)` here, where `m` is count of such incomplete links and `n` is length of the paragraph. 

With '<b' instead of 'b' (and parser doing the respective re-interpretation), it is `O(2 * m * n)`.

And I just hope that it is not possible to compose the things together in some very evil way leading to exponential complexity. Every open opportunity to reinterpret the paragraph differently makes this danger bigger in my eyes.

(Well, to be correct, I admit that implementing the parsing of '(...)' in one-pass fashion is maybe possible, but given how variadic the definition of '(...)' portion is, such algorithm would be probably pain in the ass for maintenance, and I am not aware of any implementation going that way.)

So, given how links with addresses beginning with '<' are rare, I would rather vote for banning them and not over-complicating link parsing that much. Please, lets updating the specs in some reasonable way instead to allow the early decision.

**Comment by aidantwoods** [comment]
Maybe this deserves a separate issue, but it's mostly relevant to this one. I've just realised that the spec doesn't specify a preference in which type of [link destination] to use when defining the [inline link]. And in not specifying a preference, some unintentional behaviour is perhaps *"correct"*.

> A [link destination] consists of either
> * a sequence of zero or more characters between an opening `<` and a closing `>` that contains no spaces, line breaks, or unescaped `<` or `>` characters, or
> * a nonempty sequence of characters that does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses that is not itself inside a balanced pair of unescaped parentheses.

The spec then goes on to say when defining the [inline link]
> ...The link’s URI consists of the link destination, excluding enclosing `<...>` if present,...

Initially I read that to mean that the first type of [link destination] is preferred, but that's not what it does (because the two types of [link destination] are not mutually exclusive – i.e. something that has surrounding `<...>` is only a necessary condition to be of type one, and is not a sufficient condition to exclude it from being of type two). Thus that line could apply to either [link destination] format for instance,

```
[a](<he<llo>)
```

This is not of type one, because it contains an unescaped `<`, but is of type two. However the spec says that because surrounding `<...>` are present, then they should be stripped (the reference parser does not strip the surrounding angle brackets though).


[link destination]: http://spec.commonmark.org/0.27/#link-destination
[inline link]: http://spec.commonmark.org/0.27/#inline-link

**Comment by mgeier** [comment]
@mity 

About your complexity considerations:

Sure, the number of "active characters" in the source text has an influence on complexity, but that's just a fact of life, isn't it?
So you don't really have to mention `m` in your calculations.

If parsing for the first rule isn't quadratic, parsing both rules one after each other will not be quadratic either, let alone exponential.

Also, in your example you are showing the problem with *link titles*. On the one hand, those are more complex, because they have fewer disallowed characters. On the other hand, they are less complex because the first character decides which of the three rules it will be.
Either way, there is no interaction between *link destinations* and *link titles* (at least not yet, this might change [if spaces are allowed in *link destinations*](https://talk.commonmark.org/t/allowing-whitespaces-in-link-urls/2386)!), so they can be considered separately.

Sure, properly implementing both rules for *link destination* is annoying, but I think it is doable (and I've done it, so I actually know it's doable).

> Please, lets updating the specs in some reasonable way instead to allow the early decision.

If we find a *reasonable* way, that's great.
I consider the current behavior of the reference implementations not reasonable.

@aidantwoods 

Good catch!

This is indeed a different issue, and I think the "if present" should be changed to something like "if the first rule was used" (but in a better wording!).

**Comment by DemiMarie** [comment]
One thing that is absolutely clear to me is that it **must** be possible to parse CommonMark in strictly linear time.  For CommonMark parsers, parsing untrusted input is the norm, not the exception.  Any superlinear complexity creates a denial of service vulnerability.

**Comment by jgm** [comment]
+++ Demi Marie Obenour [Jul 11 17 11:53 ]:
>   One thing that is absolutely clear to me is that it must be possible to
>   parse CommonMark in strictly linear time. For CommonMark parsers,
>   parsing untrusted input is the norm, not the exception. Any superlinear
>   complexity creates a denial of service vulnerability.

Agreed.  This has guided some decisions in designing the
parser and even the spec.

**Comment by mity** [comment]
>  One thing that is absolutely clear to me is that it must be possible to parse CommonMark in strictly linear time. For CommonMark parsers, parsing untrusted input is the norm, not the exception. Any superlinear complexity creates a denial of service vulnerability.

I'm afraid strictly linear time is impossible. 

Proof: For example number of link reference definitions in a document can grow lineary with the document size, as can number of link references, but lookup of link reference definition cannot be better then `O(log(n))`, making overall complexity about `O(n * log(n))`.

**Comment by nwellnhof** [comment]
> but lookup of link reference definition cannot be better then O(log(n))

Can't you use a hash table to look up link references in O(1)?

**Comment by mity** [comment]
Yep. I was wrong, as it was already discussed here: https://talk.commonmark.org/t/why-is-md4c-so-fast-c/2520/8?u=mity

**Comment by mgeier** [comment]
The spec has been changed in c1e0183685e22282cbf5651970200fe56a712002.

IIUC, this means for the examples above:

`[a](<b)c`: no link, just the literal characters "\[a\](\<b)c"

`[a](<b)c>)`: a link with text "a" and link destination "b)c"

`[a](<b)c>`: no link, just the literal characters "\[a\](\<b)c\>"

`[a](<b) c>`: no link, just the literal characters "\[a\](\<b) c\>"

`[a](<b>c)`: no link, but the literal characters "\[a\](", followed by the inline HTML tag `<b>`, followed by the literal characters "c)" (which are probably shown in a bold font by the browser)

Did I get this right?

I think this is a good fix for the spec, but I think some of those special cases should be added as automated spec tests.
And then of course, most implementations will have to be updated.

**Comment by Crissov** [comment]
I believe the result of `[a](<b>c)` should be equivalent to `[a](<b> c)` and `[a](b c)`. I want `c` to be interpreted as an info string, but that is a separate issue.

**Comment by jgm** [comment]
@mgeier you're right on all these cases, I think.
Note that cmark currently gets one wrong:
```
% cmark
[a](<b) c>
^D
<p><a href="%3Cb">a</a> c&gt;</p>
```

Do you have thoughts about which would be best for spec tests?  I like to keep the spec examples illustrative and not clutter the spec too much; cmark also has a regression test file to which some of these could be added.
