### ISSUE TITLE
Codespan containing single space.

### ISSUE THREAD

**Issue by mity** [commonmark/commonmark-spec#569]
I noticed the recent changes to the specs regarding code spans and the new rules for eating just one initial and trailing spaces.

Currently, for single space between backticks, cmark renders an empty code span:

``` bash
$ echo '` `' | ./build/src/cmark
<p><code></code></p>
```

But it would imho be better to render a code span with single space instead.

Rationale:
1. If you want code span with one space, it is natural way how to write single space; and imho it is more important then easy way to create empty code span. (Who needs empty code span? It is likely rendered so that user cannot see anything anyway).
2. The current specs wording does not indicate that single space can be eaten twice, by opener as well as closer marker. (And if it is intended, it imho should explicitly declare it.)

Either way, the specs should imho contain an example documenting how to render the given input.

**Comment by jgm** [comment]
I'm moving this to the spec repository, since the spec is vague here.  I'm fairly convinced that we should make a change here.  Whatever changes are made will of course have to be made in implementations.

The idea I like best is to add the phrase
```
   If the resulting string both begins *and* ends with a [space]
   character,
+ and does not consistent entirely of [space] characters
```
In cmark we're already traversing the whole string looking for newlines, so we can easily keep track of whether a nonspace character has been seen.  This allows code spans with any number of spaces, which I think we want.

Drawbacks to making a change:  You can no longer express "empty code span" in markdown.  I don't like this kind of expressive limitation.  And note that you can create a code span with one space (with current behavior) by putting three spaces between backticks.

**Comment by mity** [comment]
```
- consistent
+ consist
```

**Comment by Crissov** [comment]
You cannot express “empty emphasis span” or empty link in Commonmark either: `foo **** bar <> baz`. You can, however, express an empty link: `foo []() bar`, but not with references.

**Comment by mity** [comment]
> Drawbacks to making a change: You can no longer express "empty code span" in markdown. I don't like this kind of expressive limitation.

Then maybe it could be redefined so that a code span has 

1. an opener made by backtick sequence followed by single space and closer made by space followed by backtick sequence of the same length; or (if that is not possible)
2. opener and closer both made by just backtick sequences of the same length.

Then one space would render as one space; and two spaces would render as empty code span. Currently empty code span can be rendered both by single space or two spaces which is too generous...

**Comment by jgm** [comment]
Thinking about both of these comments, I'm coming
around to not worrying much about making empty code
spans inexpressible.  Much more important to make it
easy and natural for writers to express "code span
with one space" and "code span with two spaces."
