### ISSUE TITLE
Proposal: == for the <mark> highlight element

### ISSUE THREAD

**Issue by loup-brun** [commonmark/commonmark-spec#649]
I’m adding the suggestion of the `==` fence for the [HTML `<mark>` element](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-mark-element).

**Example:**

```markdown
I would like to ==highlight a passage==
without having to type the <mark> tag.
```

The topic has been discussed in the past on this [thread](https://talk.commonmark.org/t/highlighting-text-with-the-mark-element/840), however with no apparent outcome.

The double equal signe `==` appears to be a simple, yet preferred syntax.

This syntax is supported by some Markdown editors, such as [Typora](https://typora.io/), [iA Writer](https://ia.net/writer) (see [this update](https://ia.net/writer/blog/new-pdf-preview-better-web-publishing-improved-editing)) or the [Remarkdown renderer](https://github.com/jonschlinkert/remarkable/tree/dev#syntax-extensions).

**Comment by vassudanagunta** [comment]
@loup-brun The issues database here is for registering flaws and inconsistencies in the spec, not recommendations for extensions. That's what the talk.commonmark.org is for. There reason there hasn't been "apparent outcome" is because CommonMark is focused on standardizing Markdown, not extending it. There are lots of calls to extend it in a v1.1. or v2, but the forum is the place to make your case. There are third-party supersets of CommonMark (e.g. GFM) that aren't focused solely on the base standard as CommonMark is.  You might try to make your case with any of them.

**Comment by loup-brun** [comment]
@vassudanagunta thank you for you response!
I’ll move back to the forum and try to foster support there.
