### ISSUE TITLE
HTML comments cannot contain the string `--`

### ISSUE THREAD

**Issue by UziTech** [commonmark/commonmark-spec#662]
The [html comments spec](https://spec.commonmark.org/0.29/#html-comment) lists a few restrictions for inline comments however block comments don't have these restrictions creating issues such as https://github.com/markedjs/marked/issues/1738#issuecomment-670138374 and producing "technically" invalid html.

Should the html block spec be updated to include these restrictions?

**Comment by alerque** [comment]
I believe part of the problem here is that various incantations of the HTML spec have toggled back and forth on this, creating quite a bit of whiplash in browsers and other parsers. Whether `--` inside a comment should split the comment into two separate chunks, whether it should end it, make it invalid, or do nothing has been debated and re-implemented so many different ways it's a Gordian knot.

My suggestion would probably be do err on the side of being easier to parse accurately and quickly. Since this is content that could easily occur naturally in a block being commented out disallowing something inside a comment that isn't the end-comment syntax seems like the not-useful thing to do. Hence I put in my vote for removing that restriction from inline comments instead. Comments –whether inline or block– should be allowed to contain anything that isn't a valid end tag.

**Comment by jgm** [comment]
The spec allows you to insert bad HTML in general -- not just with comments.  It won't give you bad HTML output if you don't give it bad HTML input -- but garbage in, garbage out.

What is needed is a way to include raw HTML, and the spec provides that.  Requiring each conforming commonmark parser to include an accurate HTML5 parser is overkill for our purposes.

**Comment by DavidAnson** [comment]
@UziTech @alerque @jgm 

The [CommonMark specification seems clear](https://spec.commonmark.org/0.29/#html-comment) that "--" is NOT allowed in an HTML comment. But the [CommonMark dingus seems to HONOR](https://spec.commonmark.org/dingus/?text=before%0A%0A%3C!--%20comment%20--%20comment%20--%3E%0A%0Aafter%0A) comments that include "--" (among other things that should not be allowed). This seems incorrect regardless of what the latest HTML specification says. Is there more to this than I'm aware of so far?

Context: I have a related issue in [markdownlint](https://github.com/DavidAnson/markdownlint) and am trying to determine exactly what qualifies as a comment in CommonMark.

Thanks!

**Comment by jgm** [comment]
@DavidAnson It depends on whether we're talking about inline HTML or HTML blocks.
With the former, `--` is not allowed in comments.

```
a <!-- hi -- there -->
```

With the latter, it is:

```
<!-- hi -- there -->
```
That is because the rules for blocks are simpler and more forgiving (to allow line-by-line parsing with no backtracking).
See section 4.6, start/end condition 2.

**Comment by DavidAnson** [comment]
Thanks! Having thought about this more, the logic @alerque shared above makes me inclined to be more permissive about recognizing comments in my linter because ignoring something that is not technically a comment seems preferred to incorrectly reporting issues in commented content.
