### ISSUE TITLE
Changing functionality with darkmode

### ISSUE THREAD

**Issue by justinkterry** [commonmark/commonmark-spec#673]
There needs to be a way to describe different things to happen if the website rendering the markdown is using a darkmode or lightmode. Without this, you get things like the images in the selected projects section of this readme.md file: https://github.com/niklasf/python-chess. In github darkmode, 2 and a half of the logos are invisible. There's no general and sensible way for this to be handled without serving different ones for darkmode, and markdown doesn't support this. For website favicons, they actually had to support this functionality too due to the rise in dark mode. Perhaps some sort of pairs could be used to encode this without if statements, like these:

#Lightmode
#Darkmode:

**Comment by jgm** [comment]
I think this is too special-case for even a syntax extension.
If you're targeting HTML, you can always embed raw HTML.

**Comment by Crissov** [comment]
That’s a job better left to CSS.

**Comment by alerque** [comment]
There are *so* many ways to approach this functionality (several for each output format that potentially runs into this, HTML being the most common but not the only) and none of the formats have a normalized data representation of this (because it's somewhere between style and function, not content) that it doesn't make any sense at all to bake it into the content syntax.
