### ISSUE TITLE
Invalid em + strong rendering in JavaScript implementation

### ISSUE THREAD

**Issue by reorx** [commonmark/commonmark-spec#704]
**Describe the bug**

`a***\[1\]***b` is rendered `a***[1]***b`

**To Reproduce**
[dingus demo](https://spec.commonmark.org/dingus/?text=a***%5C%5B1%5C%5D***b%0A%0Aa***1***b)

**Expected behavior**
It should be rendered as `a<em><strong>[1]</strong></em>b`, like [Example 415](https://spec.commonmark.org/0.30/#example-415) in CommonMark spec.

P.S. This issue has also been reported to marked, but a conclusion should first be made in CommnMark's authority: https://github.com/markedjs/marked/issues/2440

**Comment by wooorm** [comment]
I believe the spec explains this correctly (albeit that emphasis/strong is super complex). To add to John, Example 415 uses an alphanumeric character (as in: non-whitespace, non-punctuation) both after the one sequence and before the other. Your example instead uses punctuation characters before/after. The characters before/after sequences make things “flanking”. And that results in differences, which I see as properly documented.

**Comment by reorx** [comment]
Thanks for your replies, I didn't notice the flanking part before, will try to read and understand more.

> if you use a numerical entity for a and b, it will change the flankingness calculations.

Is this the only way to get `a<em><strong>[1]</strong></em>b` renderer? The numerical entity is not very practical when writing.

**Comment by wooorm** [comment]
Given your problem: turn emphasis, strong runs that *do not form* into things that *do form*, then yes, I believe character references are the only complete way to change “flankingness” without changing the content (as in, you could also add some whitespace if you control the content).
That’s because they can change any character (whitespace, alphanumeric, punctuation) into a punctuation character.
Character escapes (`\+`) do not apply to “flankingness” as they don’t change the “category” of a character.

It’s rather complex to wrap your head around it all, but I recently ran across a similar AST problem, where users could include arbitrary content amongst emphasis and strong elements, and I had to serialize it as markdown that would roundtrip. It’s long but it might be interesting: https://github.com/syntax-tree/unist/discussions/60#discussioncomment-2111096

**Comment by jgm** [comment]
Another workaround, of course, is just to use raw HTML `<em>` and `<strong>` tags.
That will be more readable in this particular case (assuming you're only targeting HTML).

**Comment by reorx** [comment]
It's clear enough, thanks for all the kind help, leave you to decide whether this issue should be closed or not.
