### ISSUE TITLE
custom tag and html built-in tag are rendered inconsistently

### ISSUE THREAD

**Issue by mantou132** [commonmark/commonmark-spec#758]
[example](https://spec.commonmark.org/dingus/?text=%3Cgbp-example%0Atitle%3D%22dy-avatar-group%22%3E%0A%0A%3C%2Fgbp-example%3E%0A%0A%0A%3Cdetails%0Atitle%3D%22dy-avatar-group%22%3E%0A%0A%3C%2Fdetails%3E): 

```md
<gbp-example
title="dy-avatar-group">

</gbp-example>


<details
title="dy-avatar-group">

</details>
```

current render result:

```html
<p><gbp-example
title="dy-avatar-group"></p>
</gbp-example>
<details
title="dy-avatar-group">
</details>
```

Custom elements must have a [closing tag](https://html.spec.whatwg.org/multipage/syntax.html#elements-2), so rendering should be equivalent to `<details>`.

**Comment by jgm** [comment]
gbp-example is not recognized as a block-level tag, so this is parsed as raw inline HTML.  As inline content, it gets put in a paragraph. Of course that's not what you intended, but it's in accord with the spec.

Since this is a custom tag, there's simply no way to know whether it's intended as inline or block level content.

Your best bet is to change the input a bit so that you have a type 7 [raw HTML block](https://spec.commonmark.org/0.30/#html-block).  For this, the whole tag has to be on a line, followed by end of line.

```
<gbp-example title="dy-avatar-group">

</gbp-example>
```

You say:

> Custom elements must have a closing tag. 

Perhaps your thought is that we could defer classification of the element until we've finished the paragraph -- if we haven't hit a matching closing tag, we can take it as block-level.

I think that's too fancy, and it goes against our aim of being able to discern block-level content on a line-by-line basis.

**Comment by mantou132** [comment]
Thank you for your explanation
